swagger: '2.0'
info:
  description: This API corresponds to the use cases for the CS 3733 Group Project for team QuakeC. 
  version: 1.0.0
  title: CS3733 API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: administrator
  description: Administrators or owners of a team
- name: participant
  description: Non-administrator members of a team

paths:
  /createchoice:
    post:
      tags:
      - participant
      summary: create a new choice
      operationId: createChoice
      description: Adds a new choice to the team with empty alternatives
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: title
        description: Title of the choice to add
        type: string
        required: true
      - in: query
        name: description
        description: A brief description of the choice to be added
        type: string
        required: true

      responses:
        201:
          description: choice created
          schema:
            $ref: "#/definitions/Choice"
        400:
          description: invalid input, object invalid
        409:
          description: an existing choice already exists

  /participatechoice:
    post:
      tags:
      - participant
      summary: participate in a choice
      operationId: participateChoice
      description: Become a participant in an existing choice in the team
      
      consumes:
      - application/json
      parameters:
      - in: query
        name: id
        description: The uuid of the desired choice
        type: string
        format: uuid
        required: true
      
      responses:
        200:
          description: participation successful
        400:
          description: invalid input, object invalid
        404:
          description: desired choice not found
          
  /addfeedback:
    post:
      tags:
      - participant
      summary: add feedback to alternative
      operationId: addFeedback
      description: Using reference to member and alternative ids, adds feedback with content to an alternative
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: contents
        description: The message content of the feedback
        type: string
        required: true
      - in: query
        name: alternativeNumber
        description: number of the alternative the feedback will be  added to
        type: integer
        required: true
    
      responses:
        201:
          description: feedback added
          schema:
            $ref: "#/definitions/Feedback"
        400:
          description: invalid input
  /selectapproval:
    post:
      tags:
      - participant
      summary: select approval of alternative
      operationId: selectApproval
      description: Participant selects approval of an alternative
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: query
          name: alternativeNumber
          description: number of the alternative the approval will be  added to
          type: integer
          required: true
      responses:
        200:
          description: selected approval
        400:
          description: failed to select approval
  /selectdisapproval:
    post:
      tags:
      - participant
      summary: select disapproval of alternative
      operationId: selectDispproval
      description: Participant selects disapproval of an alternative
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: query
          name: alternativeNumber
          description: number of the alternative the disapproval will be  added to
          type: integer
          required: true
      responses:
        200:
          description: selected disapproval
        400:
          description: failed to select disapproval
  /unselectapproval:
    post:
      tags:
      - participant
      summary: unselect Approval of alternative
      operationId: unselectApproval
      description: Participant unselects disapproval of an alternative
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: alternativeNumber
        description: number of the alternative the approval will be subtracted to
        type: integer
        required: true
      responses:
        200:
          description: unselected approval
        400:
          description: failed to unselect approval
  /unselectdisapproval:
    post:
      tags:
      - participant
      summary: select disapproval of alternative
      operationId: unselectDispproval
      description: Participant unselects disapproval of an alternative
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: alternativeNumber
        description: number of the alternative the disapproval will be subtracted to
        type: integer
        required: true
      responses:
       200:
        description: unselected disapproval
       400:
        description: failed to unselect disapproval
  /completechoice:
    post:
      tags:
      - participant
      summary: call the choice
      operationId: completeChoice
      description: Participant calls the choice
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: contents
        description: The message content of the feedback
        type: string
        required: true
      responses:
        200:
          description: complete choice
        400:
          description: failed to complete choice
  /producereport:
    get:
      tags:
      - administrator
      summary: produce report of choices
      operationId: produceReport
      description: admin receives a listing of all choices
      produces:
      - application/json
      responses:
        200:
          description: report generated
        400:
          description: failed to generate report
  /deletestale:
    post:
      tags:
      - administrator
      summary: delete stale choices
      operationId: deleteStale
      description: admin deletes all choices that are older than a specified amount
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: numDays
        description: The message content of the feedback
        type: integer
        required: true
      responses:
        200:
          description: stale choices deleted
        400:
          description: failed to delete stale choices
      
definitions:
  Choice:
    type: object
    required:
      - name
      - id
      - description
      - memberCount
      - alternatives
      - alternativeChosen
      - chosenAlternative
    properties:
      name:
        type: string
        example: Hire Interns
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      description:
        type: string
        example: Does our office want to hire three additional interns?
      memberCount:
        type: integer
        example: 5
      alternatives:
        type: array
        items:
          $ref: "#/definitions/Alternative"
      alternativeChosen:
        type: boolean
      chosenAlternative:
        $ref: "#/definitions/Alternative"
        
  Alternative:
    type: object
    required:
      - number
      - name
      - feedback
      - approvals
      - disapprovals
    properties:
      number:
        type: integer
      name:
        type: string
      feedback:
        type: array
        items:
          $ref: "#/definitions/Feedback"
      approvals:
        type: array
        items:
          type: string
      disapprovals:
        type: array
        items:
          type: string
  
  Feedback:
    type: object
    required:
      - id
      - member
      - contents
    properties:
      id:
        type: string
        format: uuid
        example: 91461625-77c9-401f-a559-ae1ef4a87a36
      member:
        type: string
        example: steve
      contents:
        type: string
        example: Hiring an intern would improve productivity
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /QuakeC/QuakeCProject/1.0.0
schemes:
 - https